module.exports = [
    "amateur",
    "animal",
    "anorak",
    "ape",
    "ape covered in human flesh",
    "apefucker",
    "arfarfan'arf",
    "arse",
    "arsebreath",
    "arsecunt",
    "arseface",
    "arsehole",
    "arse-licker",
    "ass",
    "assaholic",
    "assbutt",
    "ass clown",
    "asscunt",
    "assface",
    "assfag",
    "assfaggot",
    "assfucker",
    "asshat",
    "asshole",
    "ass-kisser",
    "assmonkey",
    "assmouth",
    "assmunch",
    "ass-nugget",
    "ass sucker",
    "asstard",
    "asswagon",
    "assweed",
    "asswipe",
    "aunt fucker",
    "baby",
    "backwoodsman",
    "badass",
    "badgerfucker",
    "bag of dicks",
    "ballkicker",
    "bandit",
    "bangsat",
    "barbarian",
    "Barbie-fucker",
    "bastard",
    "beast",
    "beetlehead",
    "beginner",
    "beldame",
    "bell-end",
    "berk",
    "bespawler",
    "bimbo",
    "birdbrain",
    "birdfucker",
    "bitch",
    "bitch ass motherfucker",
    "bitch boy",
    "bitchcunt",
    "bitchface",
    "bitchfucker",
    "bitchtits",
    "bitchwad",
    "bitchwhore",
    "bitchzilla",
    "biznatch",
    "blackguard",
    "blaggard",
    "blockhead",
    "blubber gut",
    "bluntie",
    "bogeyman",
    "bonehead",
    "boob",
    "booby",
    "boomer",
    "bootlicker",
    "boozer",
    "boyfucker",
    "bozo",
    "brotherfucker",
    "bruh",
    "buffoon",
    "bugfucker",
    "bugger",
    "bum",
    "bumbo",
    "bum chum",
    "bum-fucker",
    "burden",
    "buttass",
    "buttbreath",
    "buttfucker",
    "butthead",
    "butthole",
    "buttkisser",
    "buttlicker",
    "buttmunch",
    "butt sniffer",
    "camelfucker",
    "catfucker",
    "caveman",
    "chauvinist",
    "chav",
    "cheater",
    "chicken",
    "chickenfucker",
    "childfucker",
    "chode",
    "chump",
    "churl",
    "clithead",
    "clown",
    "cock",
    "cockalorum",
    "cockboy",
    "cockburger",
    "cockfucker",
    "cockhead",
    "cockholster",
    "cockmaster",
    "cockroach",
    "cocksucker",
    "cockwaddle",
    "cockweasel",
    "cockwomble",
    "con man",
    "con merchant",
    "coomer",
    "corpsefucker",
    "cougar",
    "country bumpkin",
    "cousinfucker",
    "cow",
    "coward",
    "cowfucker",
    "crackhead",
    "crack whore",
    "craphole",
    "creep",
    "cretin",
    "crook",
    "cuckold",
    "cumbucket",
    "cum dumpster",
    "cum-licker",
    "cumslut",
    "cumstain",
    "cunt",
    "cuntass",
    "cuntbiscuit",
    "cuntbitch",
    "cuntbreath",
    "cuntface",
    "cunt fart",
    "cuntfucker",
    "cuntlicker",
    "cunt muncher",
    "cunt rag",
    "cuntshit",
    "cuntsucker",
    "cuntzilla",
    "dandiprat",
    "daughterfucker",
    "deadhead",
    "degenerate",
    "der-brain",
    "desperado",
    "devil",
    "dick",
    "dickass",
    "dickbag",
    "dickbreath",
    "dickcheese",
    "dickface",
    "dickfucker",
    "dickhead",
    "dickhole",
    "dickless",
    "dicklicker",
    "dick mouth",
    "dick sniffer",
    "dicksplash",
    "dick-sucker",
    "dicktard",
    "dickwad",
    "dickweasel",
    "dick weed",
    "dildo",
    "dillhole",
    "dimmadumbass",
    "dimwit",
    "ding-head",
    "dingleberry",
    "dinosaur",
    "dipfuck",
    "dirtbag",
    "dirthead",
    "dirtwad",
    "dodo",
    "dog",
    "dogbolt",
    "dogbreath",
    "dogfucker",
    "dolt",
    "donkey",
    "donkey dick",
    "donkeyfucker",
    "doofus",
    "dope",
    "dotterel",
    "douche",
    "douche bag",
    "doucheburger",
    "douche canoe",
    "douchefag",
    "douchelord",
    "douche nozzle",
    "douchewad",
    "douchewagon",
    "dracula",
    "dreamer",
    "drunkard",
    "duckfucker",
    "dumbarse",
    "dumbass",
    "dumbbell",
    "dumb fucker",
    "dumbo",
    "dummy",
    "dunce",
    "duncebucket",
    "dweebling",
    "earthworm",
    "edgelord",
    "egghead",
    "egotist",
    "envirotard",
    "eunuch",
    "fag",
    "faggot",
    "faggotface",
    "fagtard",
    "fagtits",
    "farmer",
    "fart",
    "fartface",
    "fatfuck",
    "fatherfucker",
    "fatso",
    "fat-tard",
    "fatty",
    "fellow",
    "fetus",
    "fibber",
    "fink",
    "fish",
    "fishwife",
    "fixer",
    "flake",
    "fool",
    "freak",
    "fruitcake",
    "fuck",
    "fuckass",
    "fuckbait",
    "fuckbucket",
    "fucker",
    "fuckhead",
    "fucking bitch",
    "fucklord",
    "fuck noggin",
    "fucknose",
    "fuck nugget",
    "fuckrod",
    "fuckskull",
    "fuckstain",
    "fuckster",
    "fucktard",
    "fucktoy",
    "fuckweasel",
    "fuckwhistle",
    "fuckwit",
    "fugly",
    "gawk",
    "gaytard",
    "geebag",
    "gimp",
    "git",
    "gobshite",
    "gold digger",
    "goof",
    "goon",
    "goose",
    "gorilla",
    "grandmotherfucker",
    "greeniac",
    "grouch",
    "grumpy",
    "handfucker",
    "headass",
    "helldog",
    "hikikomori",
    "hilding",
    "hillbilly",
    "hippie",
    "ho",
    "hobbledehoy",
    "hoe",
    "homo",
    "hooligan",
    "hooplehead",
    "horsefucker",
    "horse's ass",
    "horse's necktie",
    "hosebag",
    "hussy",
    "hypocrite",
    "idiot",
    "idiotist",
    "ignoramus",
    "imbecile",
    "inbred",
    "intercourser",
    "jabroni",
    "jackass",
    "jackhole",
    "jackwagon",
    "jagweed",
    "jelly",
    "jerk",
    "jerkoff",
    "jerkwad",
    "jit stain",
    "jizz guzzler",
    "joe mama",
    "joker",
    "junkie",
    "karen",
    "keyboard warrior",
    "kidfucker",
    "lamebrain",
    "landwhale",
    "langer",
    "lard face",
    "liar",
    "libtard",
    "lobotomite",
    "loser",
    "louse",
    "low-life",
    "lunatic",
    "lunkhead",
    "lurdane",
    "lush",
    "mackerel",
    "madman",
    "maggot",
    "mamzer",
    "meanie",
    "megabitch",
    "megadouche",
    "minx",
    "missing link",
    "mongoose",
    "monkey",
    "monkeyface",
    "monster",
    "moron",
    "motherfucker",
    "mousefucker",
    "mouthbreather",
    "Mr. Anger",
    "Mr. Obsessed",
    "Mr. Struggle",
    "Mr. Talk",
    "mucky pup",
    "muppet",
    "mutant",
    "mutt",
    "neanderthal",
    "neckbeard",
    "necrophiliac",
    "ne'er-do-well",
    "nephew fucker",
    "nerd",
    "nerf herder",
    "niece fucker",
    "nimrod",
    "nincompoop",
    "ninny",
    "nitwit",
    "nobody",
    "non",
    "nonce",
    "noob",
    "noodle",
    "numbnuts",
    "numbskull",
    "numpty",
    "numskull",
    "oaf",
    "oddball",
    "ogre",
    "oompa loompa",
    "orphan",
    "outlaw",
    "oxygen thief",
    "pack",
    "pain in the ass",
    "pariah",
    "peasant",
    "penchod",
    "pencil dick",
    "penis face",
    "pervert",
    "pig",
    "pigfucker",
    "piggy-wiggy",
    "pikspiller",
    "pillock",
    "pinhead",
    "pirate",
    "pissbrain",
    "pissbreath",
    "pissface",
    "pleb",
    "plonker",
    "pooface",
    "poohead",
    "porno freak",
    "prick",
    "prickface",
    "pseudo-intellectual",
    "pube flosser",
    "pudwhacker",
    "pukeball",
    "puppet",
    "pussyboy",
    "pussyfucker",
    "quack",
    "quat",
    "queer",
    "queer bait",
    "querulant",
    "raasclaat",
    "rabbitfucker",
    "rat",
    "ratcatcher",
    "ratfink",
    "ratfucker",
    "redneck",
    "reject",
    "retard",
    "riff-raff",
    "roaster",
    "robot",
    "rowdy",
    "rudesby",
    "ruffian",
    "runt",
    "sadist",
    "saprophyte",
    "sausage-masseuse",
    "scobberlotcher",
    "scumbag",
    "scumbreath",
    "scumbutt",
    "scumface",
    "scumfuck",
    "scumhead",
    "scumlord",
    "scumwad",
    "scuzzbag",
    "serf",
    "sewer rat",
    "shark",
    "sheepfucker",
    "sheepshagger",
    "shill",
    "shitass",
    "shitbag",
    "shitball",
    "shitbird",
    "shitbrain",
    "shitbreath",
    "shitbucket",
    "shitbum",
    "shitcunt",
    "shitdick",
    "shit-eater",
    "shitehawk",
    "shitface",
    "shit-for-brains",
    "shitfuck",
    "shitfucker",
    "shitgoblin",
    "shithead",
    "shitizen",
    "shitlord",
    "shitneck",
    "shitnugget",
    "shitpicker",
    "shitpiss",
    "shitpot",
    "shitpuddle",
    "shitsack",
    "shit stain",
    "shitter",
    "shitweasel",
    "shmekl",
    "shrew",
    "shyster",
    "sibling fucker",
    "simp",
    "simpleton",
    "sisterfucker",
    "sister humper",
    "skank",
    "skite",
    "skullfucker",
    "skunk",
    "skunkfucker",
    "slag",
    "slave",
    "sleazewad",
    "sleeze",
    "sleeze bag",
    "slimeface",
    "slob",
    "slut",
    "slutfucker",
    "sluthead",
    "snail",
    "snake",
    "snob",
    "snollygoster",
    "snot",
    "snotball",
    "snotface",
    "snothead",
    "snotwad",
    "snowflake",
    "son of a bitch",
    "son of a motherless goat",
    "son of a whore",
    "spack",
    "sphincter",
    "square",
    "stink cunt",
    "stinker",
    "stinkhole",
    "swindler",
    "swine",
    "sycophant",
    "thief",
    "thundercunt",
    "titbag",
    "toad",
    "tool",
    "tree hugger",
    "troglodyte",
    "troll",
    "trollface",
    "trolltard",
    "turd",
    "turdball",
    "turdbucket",
    "turdpile",
    "twat",
    "twattock",
    "twatwaffle",
    "twerp",
    "twit",
    "twunt",
    "unclefucker",
    "vagina cleaner",
    "vampire",
    "vandal",
    "varmint",
    "vermin",
    "vonce",
    "wacko",
    "wallflower",
    "wanker",
    "wank stain",
    "weeze bag",
    "weirdo",
    "whore",
    "whorefucker",
    "whore's-bird",
    "whoreson",
    "windfucker",
    "windsucker",
    "wino",
    "witch",
    "womanizer",
    "worm",
    "wretch",
    "xenophobe",
    "yahoo",
    "yes-man",
    "yiffer",
    "yonker",
    "yutz",
    "zitface",
    "zoophile",
    "zounderkite"
]